export const languages = [
    { "id": "english", "value": "English" },
    { "id": "kannada", "value": "Kannada" },
    { "id": "tamil", "value": "Tamil" },
    { "id": "telegu", "value": "Telegu" },
    { "id": "malayalam", "value": "Malayalam" },
    { "id": "chinese", "value": "Chinese" },
    { "id": "hindi", "value": "Hindi" },
    { "id": "spanish", "value": "Spanish" },
    { "id": "french", "value": "French" },
    { "id": "arabic", "value": "Arabic" },
    { "id": "bengali", "value": "Bengali" },
    { "id": "portuguese", "value": "Portuguese" },
    { "id": "russian", "value": "Russian" },
]